name: barberia-api

services:
  postgres:
    image: postgres:15-alpine
    container_name: barberia-postgres
    environment:
      POSTGRES_USER: barberia
      POSTGRES_PASSWORD: barberia
      POSTGRES_DB: barberia
    ports:
      - "5433:5432"
    volumes:
      - barberia_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U barberia -d barberia"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  barberia_pg_data:
